### ISSUE TITLE
Decoding error when watch events arrive

### ISSUE THREAD

**Issue by arschles** [deis/steward-framework#51]
When a `Broker` is created via the [demo chart](https://github.com/deis/steward-demo-s3/tree/new-arch/charts/broker) and steward-cf picks it up, the loop errors with the following error:

```
E1116 22:32:32.254614       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Broker" is registered for version "steward.deis.io/v1"
22:32:32 ERROR k8s.broker loop.go:38 the watch channel was closed
22:32:32 CRITC framework.runner runner.go:60 watch closed
22:32:32 CRITC  main.go:35 error running steward-framework: watch closed
```

I believe the "unable to decode watch event" error is the root cause here. Same issue for `Instance` and `Binding` events.

**Comment by krancour** [comment]
@arschles so far I am actually unable to re-create this issue, although I have submitted the following manifest directly (i.e. I didn't use a Helm chart):

```
kind: Broker
apiVersion: steward.deis.io/v1
metadata:
  name: rds
  namespace: default
spec:
  url: http://10.0.0.152
  username: username
  password: password
```

Is it possible the source of the problem actually lies within the chart?

**Comment by krancour** [comment]
Note that I did encounter a _different_ issue-- the catalog endpoint never go called on the underlying broker.

**Comment by krancour** [comment]
Ok... I spoke too soon. This popped up just after my previous comment:

```
16:23:47 ERROR k8s.broker loop.go:38 the watch channel was closed
16:23:47 CRITC framework.runner runner.go:57 watch closed
16:23:47 CRITC  main.go:35 error running steward-framework: watch closed
```

Note, however, that the "unable to decode watch event" bit is missing. That _might_ challenge your assumption that that is the root cause... we might be dealing with the intersection of a couple different issues here.

**Comment by arschles** [comment]
@krancour I think the problem with the broker manifest that you listed above is that it's not in the `steward` namespace. are you still unable to repro this when installing it to that namespace?

**Comment by krancour** [comment]
Good catch. After creating this resource in the `steward` namespace, I am reproducing the exact same issue you reported.

**Comment by arschles** [comment]
#53 fixes the decoding error; closing.
