### ISSUE TITLE
Enable codecov integration on CI

### ISSUE THREAD

**Issue by arschles** [deis/steward-framework#6]
Partially replaces deis/steward#106

**Comment by sgoings** [comment]
This looks to be already wired correctly. Reopen if you find that it is not.

https://codecov.io/gh/deis/steward-cf/branch/master
https://codecov.io/gh/deis/steward-framework/branch/master

https://travis-ci.org/deis/steward-cf/builds/174317351#L356
https://travis-ci.org/deis/steward-framework/builds/174307562#L327

There were some questions around needing to define a `CODECOV_TOKEN` but that's [only necessary if steward\* are private repos](http://docs.codecov.io/docs/about-the-codecov-bash-uploader#section-upload-token). If they're public the TRAVIS_SLUG is the identifier of a repo: https://github.com/codecov/codecov-bash/blob/master/codecov#L389
